[package]
name = "aoc-2022-day16"
authors.workspace = true
version.workspace = true
edition.workspace = true

[dependencies]
regex = "1.7.0"
shared = { path = "../../../shared", features = ["types_2d", "pathfinding"] }
