[package]
name = "shared"
version = "0.1.0"
edition = "2021"

[dependencies]
indoc = "2.0.4"

[dependencies.itertools]
version = "0.10.5"
optional = true

[features]
default = []
types_2d = ["dep:itertools"]
pathfinding = []
