[package]
name = "shared"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies.itertools]
version = "0.10.5"
optional = true

[features]
default = ["itertools"]
itertools = ["dep:itertools"]
